# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dbc0d77b2bdc5c4dc1fd103ce3f434fbbe3ec7c0099ee53350e3a6723d18b01cbc49b5e8e545a380a4c89e11c2883c24725a4e00c4f8b0db376b9aa663d21530

test:
  secret_key_base: 4da0f5019a1b53108f371433fa905d6172e853c8e7b79d48025a29e12a9900d022e6d4411cf5fef43eb3baa90fcc3c30f70a5d436a56d1f443dbcf9ef06239c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
